apiVersion: v1
kind: Namespace
metadata:
  name: amazon-clone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  namespace: amazon-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: ahmedatefelnadi/amazon-clone:product-latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: amazon-clone
spec:
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
