apiVersion: v1
kind: Namespace
metadata:
  name: amazon-clone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
  namespace: amazon-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: auth
        image: ahmedatefelnadi/amazon-clone:account-latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: amazon-clone
spec:
  selector:
    app: account
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
