apiVersion: v1
kind: Namespace
metadata:
  name: amazon-clone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: amazon-clone
  labels:
    app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ahmedatefelnadi/amazon-clone:auth-latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: amazon-clone
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
