apiVersion: v1
kind: Namespace
metadata:
  name: amazon-clone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
  namespace: amazon-clone
  labels:
    app: cart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: ahmedatefelnadi/amazon-clone:cart-latest   # replace with your cart image
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: amazon-clone
spec:
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
