apiVersion: v1
kind: Namespace
metadata:
  name: amazon-clone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-deployment
  namespace: amazon-clone
  labels:
    app: home
spec:
  replicas: 2   # you can scale up/down
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
        - name: home
          image: ahmedatefelnadi/amazon-clone:home_page-latest   # replace with your built image
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: home-service
  namespace: amazon-clone
spec:
  selector:
    app: home
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
